### ISSUE TITLE
error with visualization 

### ISSUE THREAD

**Issue by VictorCruss** [Ayima/sitemap-visualization-tool#15]
Hello! 

I ran the code files, and while the first two run fine, the visualization one returns an error.
The error goes like this: 

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/graphviz/backend.py", line 164, in run
>     proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'dot'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/giorgos/Downloads/sitemap-visualization-tool-master/visualize_urls.py", line 240, in <module>
>     main()
>   File "/Users/giorgos/Downloads/sitemap-visualization-tool-master/visualize_urls.py", line 235, in main
>     f.render(cleanup=True)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/graphviz/files.py", line 243, in render
>     rendered = backend.render(self._engine, format, filepath,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/graphviz/backend.py", line 223, in render
>     run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/graphviz/backend.py", line 167, in run
>     raise ExecutableNotFound(cmd)
> graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Kdot', '-Tpng', '-O', 'sitemap_graph_2_layer'], make sure the Graphviz executables are on your systems' PATH
> 
> 
> 

Could you help me resolve this? 

Thank you in advance for your help,

VC

**Comment by zazencodes** [comment]
This script requires graphviz dependencies, which can be a bit tricky to install.

I have some [notes on installing graphviz](https://github.com/Ayima/sitemap-visualization-tool#dependencies) in the README for this repo.

You can also browse [this stackoverflow thread](https://stackoverflow.com/questions/35064304/runtimeerror-make-sure-the-graphviz-executables-are-on-your-systems-path-aft) for ideas on solving the problem on your operating system.

Good luck!

**Comment by VictorCruss** [comment]
Thank you for your quick reply, I have installed graphviz using`pip install graphviz' and 'brew install graphviz' and all seemed to have gone well, yet I still get the same error as before...
