### ISSUE TITLE
Interactive Graph

### ISSUE THREAD

**Issue by macd2** [Ayima/sitemap-visualization-tool#2]
Now i have one more question:
since this module is exporting a csv is it possible to sort the csv in a way that it can get pulled in to gephy or is there any other way to make the output interactive?

**Comment by zazencodes** [comment]
If you wish to integrate the outputs better with gephy or another tool, then I would encourage you to fork the project and add this feature.

From our end, we are currently working on a tool for interactive sitemap visualizations. We may be adding the source-code to this project when it's complete.
