### ISSUE TITLE
Crawler link detection

### ISSUE THREAD

**Issue by macd2** [Ayima/sitemap-visualization-tool#3]
Hello Again,
after some more testing i noticed that the crawler is not getting all the internal links. The displayed links in the .pdf are mostly menu and sidebar links but links in content area are ignored.
Can we add a setting to adjust the crawler "depth"?

**Comment by zazencodes** [comment]
Hi, this is not a crawler - but simply a tool for visualizing sitemaps.

A good way to customize the visualization is by editing the CSV file that is produced by `categorize_urls.py`, prior to running the visualization script.
