### ISSUE TITLE
.csv file

### ISSUE THREAD

**Issue by abhishekroy007** [Ayima/sitemap-visualization-tool#5]
while categorizing in csv file just two columns are generating.
![site](https://user-images.githubusercontent.com/23011140/41522725-ee15420e-72f4-11e8-8393-880fe89ca208.PNG)

**Comment by zazencodes** [comment]
Hi @abhishekroy007 , thanks for pointing this out. It's no issue with the tool - but it looks like  sportchek changed their site structure. I've changed the default depth to 4, so now you will see a better result by default.

Keep in mind you can pass any max depth you want e.g. `python categorize_urls.py --depth 5`
